### ISSUE TITLE
Sintax error

### ISSUE THREAD

**Issue by bokas** [emencia/emencia-django-newsletter#10]
I know it's not very important but there is a sintax error in the file admin/contact.py in line 94.
Where it says for "workgroup in request_workgroup(request):" it should say "for workgroup in request_workgroups(request):".
Like I said, it's not a big deal but it sure is anoying.

**Comment by Fantomas42** [comment]
Hi
thank you for the report.
I fixed it in 4842d89ee147f9f9d1b2146c1af386ad1cef1340

My mistake...
