### ISSUE TITLE
Smart_str for links header in csv report

### ISSUE THREAD

**Issue by jfache** [emencia/emencia-django-newsletter#12]
In newsletter/views/statistics.py, line 70, use the 'smart_str' function around the link.title in order to avoid UnicodeEncodingErrors. 

```
def header_line(links):
    link_cols = [smart_str(link.title) for link in links]
```

Thanks !

**Comment by Fantomas42** [comment]
Hi shao197 !
thank you for the bug report !
Fixed in 6b148f18512e8a76ed748150f8bac9f1f8d75e0f
