### ISSUE TITLE
Post importation signal

### ISSUE THREAD

**Issue by lucalenardi** [emencia/emencia-django-newsletter#14]
Hi.

I think it could be useful to have a signal to be triggered post importation inside ContactAdmin. This will make easier the extraction of other useful information form (for example) a vCard to be saved in a auxiliary model associated with Contact (e.g. Profile).

**Comment by lucalenardi** [comment]
I have a patch (not a commit) now. Is it possible to attach a file here somehow?

**Comment by lucalenardi** [comment]
I've merged my repo and committed the patch to contact.py that adds a signal to it here: https://github.com/lucalenardi/emencia-django-newsletter/commit/9bff52b59729e9c56207d55ad41f8eb8bb506461

Let me know your ideas.

**Comment by Fantomas42** [comment]
Hi, good idea and thank you for patch.

I have merged your repository with mine at a82a65e6bffe9883c2ba3ef9788c891de05ce271
and added some modifications at dafb4599032be59b90b4925d2f605c9e76dc9d93

Good work !
