### ISSUE TITLE
Can't add contact to mailing list if workgroup not activated

### ISSUE THREAD

**Issue by alexgarel** [emencia/emencia-django-newsletter#26]
If workgroup are not activated and user is not super user, it is impossible to add any contact as it filters on an empty set of workgroups.

Problem is in admin/mailinglist.py line 54 

```
if 'subscribers' in db_field.name and not request.user.is_superuser:
        contacts_pk = request_workgroups_contacts_pk(request)
        kwargs['queryset'] = Contact.objects.filter(pk__in=contacts_pk)
```

Solution may be to add a control on workgroup activation.

**Comment by Fantomas42** [comment]
Thank you for the report.

Fixed in Fantomas42/emencia-django-newsletter@18a81af81f5d78c9e1da20c13ad5c0081792a9b8
