### ISSUE TITLE
subscribe / unsubscribe forms won't work if base.html does not exists

### ISSUE THREAD

**Issue by alexgarel** [emencia/emencia-django-newsletter#27]
Taking the buildout and using the demo, the unsubscribe form was broken.

In fact it extends templates/newsletter/base.html which in turns extends base.html which is not found.

Either demo project (or new project) shall contain a base.html template, either it may test for its existence.

To circumvent this problem, I did :
- add a templates directory in my app
- add a base.html inside this directory with same content as here : http://www.djangobook.com/en/beta/chapter04/#cn330
- change my settings.py to add :
      TEMPLATE_DIRS = (
         '/home/www/emencia-django-newsletter/demo/templates',
      )

**Comment by Fantomas42** [comment]
Fixed in Fantomas42/emencia-django-newsletter@3526176edee2102b6d60ff309d7522ac238e9576
