### ISSUE TITLE
Update Chinese locale files

### ISSUE THREAD

**Issue by littlepea** [emencia/emencia-django-newsletter#32]
Hi,

Our Chinese dev finalized you Chinese translation on transifex:
http://www.transifex.net/projects/p/emencia-django-newsletter/resource/djangopo/

Could you, please, commit it?

**Comment by Fantomas42** [comment]
Hi,

sorry for the late reply. 
No problems for doing it, but it seems that the zh_CN translation has 2 fatal errors.
Lines 531 and 778, the formats are not respected.

Could you fix it ?

**Comment by littlepea** [comment]
Hi,

We've fixed it. Please, check.

## 

Evgeny Demchenko
Chief Representative of Sterno.Ru, Beijing Office

**Comment by Fantomas42** [comment]
Hi,

thank you for your support and translating EDN.
Translation added in Fantomas42/emencia-django-newsletter@4f3ce322c59cf8003c147eba2561acd9ef91ae1d

Regards
