### ISSUE TITLE
already_sent problem?

### ISSUE THREAD

**Issue by martip** [emencia/emencia-django-newsletter#4]
Hi Julien, it's me again.

I found a little problem in mailer.py.
If I understood well, the already_sent list is supposed to contain a list of Contact objects id. Instead, the following line in mailer.py (line 92 in current trunk)

```
already_sent = ContactMailingStatus.objects.filter(status=ContactMailingStatus.SENT,
            newsletter=self.newsletter).values_list('id', flat=True)
```

populates the list with ContactMailingStatus objects id!
I believe that the line should be written as:

```
already_sent = ContactMailingStatus.objects.filter(status=ContactMailingStatus.SENT,
            newsletter=self.newsletter).values_list('contact__id', flat=True)
```

What do you think?
Paolo

**Comment by Fantomas42** [comment]
Hello,
good job for this report, and effectively it seems to be a bug.

I will write some tests to raise the bug and fix it with your correction.
