### ISSUE TITLE
language of mail - possible extension

### ISSUE THREAD

**Issue by felarov** [emencia/emencia-django-newsletter#48]
How can the mailer determine the language of the client for the unsubscribe and canviewsite links. A solution would be to introduce a language field in the contact model and make the newsletter model also multilingual. Any interest ?

**Comment by Fantomas42** [comment]
Your site have a language defined by default, this is it used.

It's an interesting feature, but needs some time and brain-storming, but it's not the main aim of EDN and I don't really have time to implement it alone.

Fork and send me a pull request, is a good starting point for this feature.
