### ISSUE TITLE
Newsletter status is updated to sent although not all contacts received it.

### ISSUE THREAD

**Issue by chliviu** [emencia/emencia-django-newsletter#5]
If my mailing list consists on 2000 contacts, the SMTP server emails per hour set to 100, it will only generate 100 emails and send them, and change the newsletters status to sent. The next time the cron is ran, it doesnt create the newsletter for the other contacts because the status is sent.

My fix (line numbers may be different) in mailer.py:
<-- removed -->

**Comment by Fantomas42** [comment]
Ok I will check this, and try to reproduce the bug.

**Comment by Fantomas42** [comment]
I have wrote a test to reproduce the bug, and effectively I've made a mistake.
But it seem your fix can't work properly because, get_expedition_list is still filtered to exclude already sent message, so the value is not valid

Thank for the report, the bug is fixed !
