### ISSUE TITLE
Send newsletter with attachments

### ISSUE THREAD

**Issue by lucalenardi** [emencia/emencia-django-newsletter#6]
Are there any plans to support the delivery of newsletters with attached files?

**Comment by Fantomas42** [comment]
Not for the now, but it's a good idea.

Maybe in the future, or contribute to the project to support this feature.

**Comment by Fantomas42** [comment]
Ok support enabled by merging with your branch, and some rewrites.

http://github.com/Fantomas42/emencia-django-newsletter/commit/78778abfa585db542fa9166f0a525accc1ec2013
