### ISSUE TITLE
TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by euricojardim** [emencia/emencia-django-newsletter#67]
I wasn't able to use ./manage.py send_newsletter with timezone aware sites.

Try with django1.4 and leave TIMEZONE setting as True and it will throw TypeError: can't compare offset-naive and offset-aware datetimes.

mailer.py line 198, in can_send
    if self.newsletter.sending_date <= datetime.now()

**Comment by Fantomas42** [comment]
Hi @euricojardim,

unfortunately EDN is not already compatible with Django 1.4.

So you must use Django 1.3, or make a patch. If you do the patch, a pull request would be very appreciated.

Regards

**Comment by euricojardim** [comment]
Hi @Fantomas42,

I did the pull request as you suggested.

Regards
