### ISSUE TITLE
Suscribe to a mailing list

### ISSUE THREAD

**Issue by lucalenardi** [emencia/emencia-django-newsletter#7]
Another feature request, I suppose.

I'm looking for a simple form to let users subscribe to a mailing list within a public site. It could be something  similar to how the `view_mailinglist_unsubscribe` view works, but with the ability to create a new contact before adding it to the selected mailing list.

Do you believe that such a feature could be useful?

Thanks.

**Comment by Fantomas42** [comment]
Yes this feature could be usefull, and she's planned for the weeks to come.
I remind that I have started to look in, but a problem appears and I don't remember which.

**Comment by lucalenardi** [comment]
I've added a "very basic" support for this feature in my fork. Please, take a look at it so we can start discussing how to go further. Thanks.

**Comment by lucalenardi** [comment]
For example: it could be useful to have a flag on the MailingList model to decide whether a user can subscribe by herself or not. Something like "opened/closed to public subscription".

**Comment by Fantomas42** [comment]
I've take a look, and it's a good job !
I will merge your modifications in my branch.

But I will add a feature, instead of choosing the mailing list you want to subscribe in the form, it can be usefull to have a kind of "templatetags" or views for allowing susbscriptions directly to a mailing list.

I will try to do that tomorrow.

**Comment by Fantomas42** [comment]
Ok I've merged your modifications and adding support for independant mailing lists.
Now we can register to a single mailing list. 

But the idea to use a open/close boolean on the mailing list is not ready.
And I think I need to rewrite some code in the views and forms for the email check.

**Comment by Fantomas42** [comment]
Rewriting views, but not using boolean for open/close mailing list, the cases for using this feature are really rare.
http://github.com/Fantomas42/emencia-django-newsletter/commit/49954fb6d8525461bb53f683e86edb8c083c0d02
